### ISSUE TITLE
Mis-translated a few repeaters in my chirp export

### ISSUE THREAD

**Issue by jcragin** [emresaglam/chirp2yaesu#4]
Here is a diff that worked for me, not elegant at all but does the job so far.

`--- chirp_to_yaesu.py.orig	2017-08-25 22:24:24.451842800 -0600`
`+++ chirp_to_yaesu.py	2017-08-25 22:25:05.500422000 -0600`
`@@ -6,6 +6,34 @@`
`     foo.append(templine.split(","))`
`     return foo`
` `
`+def translateToneMode(mode):`
`+    retMode = ""`
`+    if mode == "Tone":`
`+        retMode = "TONE ENC"`
`+    elif mode == "DTCS":`
`+        retMode = "DCS"`
`+    elif mode == "":`
`+        retMode = "OFF"`
`+    else:`
`+        print ("Unknown Tone Mode: " + mode)`
`+    return retMode`
`+`
`+def translateMode(mode):`
`+    retMode = ""`
`+    if mode == "FM":`
`+        retMode = "FM"`
`+    elif mode == "NFM":`
`+        retMode = "NFM"`
`+    elif mode == "Auto":`
`+        retMode = "FM"`
`+    elif mode == "WFM":`
`+        retMode = "FM"`
`+    elif mode == "AM":`
`+        retMode = "AM"`
`+    else:`
`+        print ("Unknown Mode: " + mode)`
`+    return retMode`
`+`
` # Adding the command line flags`
` parser = argparse.ArgumentParser(description="This tool converts a chirp csv file to a Yaesu importable csv file")`
` parser.add_argument('--input', '-i', required = True)`
`@@ -22,16 +50,21 @@`
` with open(inputFile) as csvfile:`
`     reader = csv.DictReader(csvfile)`
`     for row in reader:`
`-        if row["Tone"] == "Tone":`
`+        toneMode = translateToneMode( row["Tone"] )`
`+`
`+        mode = translateMode( row["Mode"] )`
`+`
`+        if toneMode != "" and mode != "":`
`             numlines += 1`
`+`
`             ftline.append(str(numlines))`
`             ftline.append(row['Frequency'])`
`             ftline.append('')`
`             ftline.append(row['Offset'])`
`             ftline.append(row['Duplex'] + "RPT")`
`-            ftline.append(row['Mode'])`
`+            ftline.append(mode)`
`             ftline.append(row['Name'])`
`-            ftline.append("TONE ENC")`
`+            ftline.append(toneMode)`
`             ftline.append(row['rToneFreq'] + " Hz")`
`             ftline.append(row['DtcsCode'])`
`             ftline.append("1500 Hz")`

**Comment by emresaglam** [comment]
Thanks for the patch. I can merge if you want to do a pull request. :) (Or I can do a manual patch.) Let me know.
